### ISSUE TITLE
User Story 1: Setup item gallery - The biggest things do not work quickly.

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#1]
## Value Proposition

**As a** User
**I want to**  browser through all wares
**so that** I have a overview

## Description

<img width="1946" alt="Capstone_US1_description_alpha" src="https://user-images.githubusercontent.com/117607177/213680728-a2b277fd-f45f-40b4-a2ce-ffc2cd7eb2d9.png">

## Acceptance Criteria

-  [x] All items from a static JSON are displayed as cards
-  [x] In a card, the name of item is displayed
-  [x] In a card, the image of the item is displayed
-  [x] In a card, the price of the item is displayed
-  [x] The title of the app is always visible on top

## Tasks

- [x] Map over the example items from the JSON to design the cards
- [x] Create title component
- [x] Create a card component displaying the required elements
- [x] Style is in Figma using low fidelity first

## Complexity

(S)

**Comment by doemser** [comment]
I like it, good minimalist approach, I know exactly what you are up to.

**Comment by Long-HaHoang** [comment]
Updated: User Story.

- [x] Removed `...` from value proposition and complexity.
- [x] Added checkmarks, again. To the acceptance criteria.
- [x] Removed the mention of button in the description picture.
- [x] Add task to look at the figma low fidelity design
- [x] Add more description to the title.
- [x] Left the complexity as it is, because it is XS for me.

**Comment by shebtastic** [comment]
Hey Long,

great work and awesome that you tracked the changes in the checklist! :octocat: 

We have one last minor request: your description still mentions the price, but doesn't show it anywhere else. Either include the price everywhere or remove it in the mockup. 

Otherwise we're happy. Please make update the price, but we're going to give you the go ahead already.

Happy hacking! 🚀 

P.S.: keep in mind that the complexity estimate of XS is the smallest imaginable story on our scale. If you _can imagine_ a smaller task this might be misplaced. 😁 but the scale is always up to you, as the development team.

**Comment by Long-HaHoang** [comment]
- [x] Rising the complexity to S
