### ISSUE TITLE
User Story 5 - Remove items from shopping cart - The goal of management is to remove obstacles

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#10]
## Value Proposition

**As a** buyer
**I want to** remove items from the shopping cart
**so that** I can only buy items I can afford

## Description

![Capstone-US5(3)](https://user-images.githubusercontent.com/117607177/216479105-1f374bd1-8c04-4326-890a-f051e2ab079e.png)

## Acceptance Criteria

- [x] The shopping cart button is displayed in the header
- [x] The items from the shopping cart are displayed as cards
- [x] The section displays the `Shopping Cart` headline
- - [x] In the section the total amount of items and total price items
- [x] In the item card the delete button is displayed
- [x] Pressing the delete button removes the item
- [x] The summary section is displayed
- - [x] In the section the sum of items and price is displayed
- - [x] In the section the shipping cost is displayed
- - [x] In the section the total price is displayed

## Tasks

- [x] Create a summary section
- [x] Create a delete button
- [x] Apply minimum style (maybe grid)

## Complexity

Size M

**Comment by RobinWitt** [comment]
Hi Long,
just a small thing:
- [ ] The section displays the `Shopping Cart` headline ~~is displayed~~
- - [ ] In the section the total amount of items and total price of items _are displayed_

**Comment by Long-HaHoang** [comment]
Thanks for your feedback 👍
