### ISSUE TITLE
User Story 6 - Details page of items - Succes is in the details

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#11]
## Value Proposition

**As a** buyer
**I want to** see more details about a specific item
**so that** I can get more information about that item

## Description

![Capstone-US6(1)](https://user-images.githubusercontent.com/117607177/215909441-a2ad9d4e-9024-4b0a-b2db-22af32da1012.png)

## Acceptance Criteria

- [x] Clicking the title or picture of an item routes you to a details page
- [x] On the details page, the product title and category are displayed
- [x] On the details page, the back button is displayed and routes back to the homepage
- [x] On the details page, the product image is displayed
- [x] On the details page, the product description is displayed
- [x] On the details page, the add-to-cart section is displayed
- [x] In the add-to-cart section, the price, counter, add to cart button is displayed

## Tasks

- [x] Create a details page
- [x] Create a dynamic link to a details page
- [x] Create API endpoint to fetch one product
- [x] Add a section with a backlink and category paragraph
- [x] Add an article with an image and a description section
- [x] Add a fixed "menu" to the bottom with price, counter component, and the cart button
- [x] Apply minimum style (maybe grid)

## Complexity

(Size L)

**Comment by AGeck113** [comment]
Hello Long,
nice US, very well structured and clear AC. But maybe you could be a little bit more specific with the tasks at the next one 🙂

**Comment by Long-HaHoang** [comment]
Thanks for your review. 
I added some more tasks to the story.
