### ISSUE TITLE
User Story 7 - Hero section - Be your own hero

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#12]
## Value Proposition

**As a** seller
**I want to** show a buyer a featured or discounted item
**so that** I can animate a buyer to buy more

## Description

![Untitled-2023-02-08-1005](https://user-images.githubusercontent.com/117607177/217509812-46da06d7-0ef9-44eb-b192-2fd091fe082e.png)

## Acceptance Criteria

- [ ] The hero section is displayed above the shop items
- [ ] In the hero section, the title, description, and image of a featured item are displayed
- [ ] The hero section is a link, which routes the user to the details page of the featured item

## Tasks

- [ ] Create a component for the hero section
- [ ] Link to the details page
- [ ] The hero section is part of the `<main>`
- [ ] Wrap hero div with a link
- [ ] Refactor styling to minimal component count
- [ ] Install Zustand for state management
- [ ] Research other eCommerce shops about hero sections
- [ ] Refactor components to a lower count. 

## Complexity

(Size M)

**Comment by HosseinKrouna** [comment]
Hi Long,
In my opinion, the fake button is unnecessary, but it's just my professional point of view ;) otherwise good work 👍

I don't know if it will be a link or an onclick event to your details page. Or would it make a difference here?
And I don't know exactly either, but maybe you can also contact me directly as to whether my remarks are legitimate or not

**Comment by Long-HaHoang** [comment]
Yeah, the fake button is optional. Is a design thing. 
You are more likely to press something if it looks like a button.

It's a `<Link>` it will make the hero section semantic. But this gives me an idea.
Will add to the task.

**Comment by HosseinKrouna** [comment]
I'm glad I was able to give you an idea 🤓

and than happy hacking ☺️
