### ISSUE TITLE
User Story 8 - Role_change

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#18]
## Value Proposition

**As a** USER
**I want to** switch between the roles of a buyer and seller
**so that** I can see different options depending on the role

## Description

![Untitled-2023-02-08-1500](https://user-images.githubusercontent.com/117607177/218069438-f09d0c04-d519-480d-bf21-862750e7244f.png)

## Acceptance Criteria

- [x] If the user is not logged in the user should be routed to a login page
- [x] The login page doesn't show the shop header
- [x] The buttons for the fake login route the user to the respective shop
- [x] The login page displays another footer
- [x] The shop page in seller view doesn't display the counter and shopping cart
- [x] On the login page the login buttons are displayed

## Tasks

- [x] Create CRUD methods in the backend
- [x] Create a session and role state
- [x] Create a fake login page
- [x] If the user is already logged in display a logout button 
- [x] Validation and research to control site access rights
- [x] Continue to refactor styling

## Complexity

(Size L)

**Comment by niklasrammelkamp** [comment]
Hi Long, nice Story. Only on little thing. Why do you call this a fake login page? It seems like the page isn't fake. As I understand the Story, you are building a real log in.

**Comment by Long-HaHoang** [comment]
It's fake because there are no credentials needed. Just to buttons.

**Comment by Long-HaHoang** [comment]
Researching a better way to log in. Looking into [nextauth.js](https://next-auth.js.org/) (or [auth.js](https://authjs.dev/) in the future).
I need to think about the user database, state management, and data models.
