### ISSUE TITLE
User Story 2. Total Number - At the very apex of callousness, you will find only ones and zeros. 

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#2]
## Value Proposition

**As a** buyer  
**I want to**  add a number of items to the shopping cart 
**so that** I can see the total amount of items while browsing

## Description

<img width="1641" alt="Capstone_US2_description_alpha" src="https://user-images.githubusercontent.com/117607177/213768671-d18aeeee-584e-47aa-9994-7772273d0520.png">

## Acceptance Criteria

- [x] Shopping cart with indicator is displayed
- [x] Shopping cart is displayed in top right
- [x] In a card, the counter section is displayed
- [x] In the counter, the quantity is displayed
- [x] Add to cart button is displayed
- [x] Pressing the `shopping cart` button will add the current counter to the total indicator at top right
- [x] Pressing the `+` button will increase the counter
- [x] Pressing the `-` button will decrease the counter

## Tasks

- [x] Create section for counter
- [x] Create add to cart button
- [x] Create shopping cart icon with indicator
- [x] Position the price above the counter

## Complexity

(M)

**Comment by JoergWolff** [comment]
I have some comment, don't despair.
Most English words are lowercase. e.g. shopping cart.
Also something is missing:
How about the removing button and the price label?
I see it, but you don't talk about them.
I hope, i can help you on this way.

**Comment by Long-HaHoang** [comment]
Their is no removing button. It's intentional. You can remove items from the cart later in the checkout page.
The checkout page is not part of this story.
Removing and editing your cart comes later.

The price label already got added in first story. I replaced the placeholder `<price>` to `Lorem €` to make it more visible in the user story

- [x] fixed grammar issue
- [x] showing lorem price in picture

**Comment by JoergWolff** [comment]
Hi long sorry but I see a "+" and "-" button.
That's what I mean.
Why can't I use the minus already here?
And you don't talk about in your user story.
I just noticed.
I have not seen before the price label, my fault. Sorry

**Comment by Long-HaHoang** [comment]
Oh yes I should make it more clear. Adding the counter to the total is done by the shopping cart button.
Increasing and decreasing the counter is done by the counter component.
Will add to the criteria to make it more clear.

**Comment by Long-HaHoang** [comment]
- [x] fixed wording for the shopping cart indicator the make it more clear
- [x] add criteria for the `+` and `-` buttons

**Comment by JoergWolff** [comment]
You are my hero
