### ISSUE TITLE
User Story 9 - Add product to the DB

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#20]
## Value Proposition

**As a** Seller
**I want to** add more products to the shop
**so that** sell more products

## Description

![US9](https://user-images.githubusercontent.com/117607177/218313891-a5c82956-b247-49f4-b3fd-7b1cc36e364e.png)

No navigation added yet.
I will refactor/rebuild the App after the Capstone.

## Acceptance Criteria

- [ ] On the Homepage a link to the add form is displayed
- [ ] On the Adding Form Page the inputs are displayed
- - [ ] The inputs have a validation
- [ ] Submitting the form reroutes the user to a confirm page
- [ ] The new item gets a placeholder picture from the DB

## Tasks

- [ ] Add Link to a new page on the homepage only Seller View
- [ ] Adding the Post method to the submit process
- [ ] Disable submit button while the POST is ongoing
- [ ] ADD validation to the inputs <s>steal</s> kindly ask the students for it.
- [ ] Refactor styling

## Complexity

(Size M)

**Comment by AstridOttmann** [comment]
LGTM!
The only thing I miss is where you display the new item.
