### ISSUE TITLE
User Story 10 - Style and refactor

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#21]
## Value Proposition

**As a** Developer
**I want to** style my app
**so that** the user has a more pleasing experience using the app

## Description

No wireframe, yet.
The prototype design is still in Figma.
I need to adapt the design to reflect the User Journey.
I opt for a minimal design approach.

## Acceptance Criteria

- [x] The design is coherent.
- [x] No dark mode for the app
- [x] Item cards have a box-shadow
- [x] Icons are now variants
- [x] Header no longer absolute and can be scrolled away

## Tasks

- [x] Refactor the app style. Reference is in Figma
- [x] Refactor the icons the be a variants
- [x] Using grid layout for the Layout

## Complexity

(Size L)
