### ISSUE TITLE
User Story 10 - Search product.

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#23]
## Value Proposition

**As a** Buyer
**I want to** search for a specific item
**so that** I don't have to scroll the whole shop

## Description
![US - Search bar](https://user-images.githubusercontent.com/117607177/219070638-75966682-4ff4-4492-894e-c31003a0e24e.png)

Implementing a search bar.
There are different search bars in the app.
On the shop overview, the search should find shops. (Overview is a future feature)
On the shop page, the search bar should find products

## Acceptance Criteria

- [ ] On the Homepage the search bar is displayed
- [ ] The search bar is displayed above the hero section. 
- - [ ] On mobile, it is hidden by default.
- [ ] The search bar filters the product by product name
- [ ] The hero is not displayed while searching for an item
- [ ] The search bar is always displayed on the desktop

## Tasks

- [ ] Create a search bar component
- [ ] Filter the product array state to display only the searched term
- [ ] Disable the hero section if the search is not empty

## Complexity

(Size M)

**Comment by anotherMichaelMaier** [comment]
Wow, such a masterpiece. Must be the rumored a Piccasso Hoang piece. ✅
