### ISSUE TITLE
User Story 3: Connect the DB - There is noSQL for this.

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#3]
## Value Proposition

**As a** Seller  
**I want to** share the same data from a database
**so that** everybody can see my items on different devices

## Description

<img width="2115" alt="Capstone_US3_description_alpha" src="https://user-images.githubusercontent.com/117607177/213453550-fe4a534e-552e-44c0-a494-b6863659aa64.png">

## Acceptance Criteria

- [x] All items from the database are displayed as cards
- [x] In a card, the name of the item is displayed
- [x] In a card, the price of the item is displayed
- [x] Header of the app is always visible

## Tasks

- [x] Create database on MongoDB Atlas
- [x] Prepare the database connection
- [x] Create a database function to `find` all items
- [x] Create an api endpoint in your api/items route for fetching all items from the DB
- [x] Map over fetched items to render the cards

## Complexity

... (L)

**Comment by magjo21** [comment]
Hi, Looks good to me!
