### ISSUE TITLE
User Story 4 - Overview of cart items. 

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/capstone-project#7]
## Value Proposition

**As a** buyer 
**I want to** press the cart button icon
**so that** I can see an overview page of all added items in my cart

## Description

![Capstone-US4(4)](https://user-images.githubusercontent.com/117607177/216143410-11b9875e-1b0b-4910-a22e-9367fccd4c65.png)

## Acceptance Criteria

- [x] Cart routes the user to the overview page
- - [x] If the cart is empty renders a message instead of the item list
- [x] On the overview page, the backlink is displayed
- [x] In the overview page, cards of added items are displayed
- [x] In the card, a small thumbnail picture is displayed 
- [x] In the card, each item name, amount, and price are displayed
- [x] On the overview page, the sum of amounts and the total price is displayed 

## Tasks

- [x] Create the overview component
- [x] Create a section to display the total amount and price
- [x] Static route to the overview page
- [x] Apply minimum style (maybe grid)

## Complexity

(L)

**Comment by Mistake91** [comment]
Hey Long, your user story looks very good and well thougth 👍
